In [1]:
l = [24, 76, 'Hello', 8883, 8345]

In [3]:
import numpy as np

In [8]:
a = np.array(l)

In [12]:
a

array([  24,   76, 7484, 8883, 8345])

In [17]:
l.pop()

8883

In [18]:
l

[24, 76, 7484, 8345]

In [19]:
a.mean()

4962.4

In [20]:
b = np.array([24, 76.94, True, False, 8345])

In [21]:
b

array([2.400e+01, 7.694e+01, 1.000e+00, 0.000e+00, 8.345e+03])

---

In [22]:
# Slicing the arrays

In [23]:
l

[24, 76, 7484, 8345]

In [24]:
l[:]

[24, 76, 7484, 8345]

In [25]:
l[1:4]

[76, 7484, 8345]

In [26]:
l[0:3]

[24, 76, 7484]

In [27]:
a

array([  24,   76, 7484, 8883, 8345])

In [28]:
a[0:4]

array([  24,   76, 7484, 8883])

In [29]:
a[2:]

array([7484, 8883, 8345])

In [30]:
a[-4:-2]

array([  76, 7484])

In [31]:
b = a[2:4]

In [32]:
b

array([7484, 8883])

In [33]:
b[0]

7484

In [35]:
b[:] = 111

In [36]:
b

array([111, 111])

In [37]:
a

array([  24,   76,  111,  111, 8345])

In [38]:
c = a.copy()

In [39]:
c[0] = 5

In [40]:
c

array([   5,   76,  111,  111, 8345])